name:                async-scattered
version:             0.1.0.0
github:              "Anteproperispomenon/async-scattered"
license:             BSD3
author:              "David Wilson"
maintainer:          "example@example.com"
copyright:           "2022 David Wilson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/async-scattered#readme>

dependencies:
- base >= 4.7 && < 5
- async
- hashable
- list-t
- stm
- stm-containers

library:
  source-dirs: src
  default-extensions:
    - DataKinds
    - ImportQualifiedPost
    - KindSignatures
    - LambdaCase
    - MultiWayIf
    - NumericUnderscores
    - RankNTypes
    - ScopedTypeVariables
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns

executables:
  async-scattered-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async-scattered

tests:
  async-scattered-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
      - DataKinds
      - ImportQualifiedPost
      - KindSignatures
      - LambdaCase
      - MultiWayIf
      - NumericUnderscores
      - ScopedTypeVariables
      - TupleSections
      - TypeApplications
      - TypeOperators
      - ViewPatterns
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async-scattered
